In [14]:
import requests
def current_weather():
    api_key="c096eadd3c5a43663bee27c7c3b53a05"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    weather_data=response1.json();
    print(json.dumps(weather_data,indent=5))
    des=weather_data["weather"][0]["description"]
    tem=weather_data["main"]["temp"]
    pre=weather_data["main"]["pressure"]
    hum=weather_data["main"]["humidity"]
    vis=weather_data["visibility"]
    ws=weather_data["wind"]["speed"]
    print("***************************************************************************************************************************************")
    print("***************************************************************************************************************************************")
    print(f"Description : {des}")
    print(f"Temprature  : {tem}")
    print(f"Pressure    : {pre}")
    print(f"Humidity    : {hum}")
    print(f"Visibility  : {vis}")
    print(f"Wind Speed  : {ws}")
current_weather()

Enter the City name:  Rajkot

{
     "coord": {
          "lon": 70.8028,
          "lat": 22.3053
     },
     "weather": [
          {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 307.11,
          "feels_like": 312.86,
          "temp_min": 307.11,
          "temp_max": 307.11,
          "pressure": 1010,
          "humidity": 54,
          "sea_level": 1010,
          "grnd_level": 993
     },
     "visibility": 10000,
     "wind": {
          "speed": 5.93,
          "deg": 247,
          "gust": 6.67
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779767164,
     "sys": {
          "type": 2,
          "id": 2104500,
          "country": "IN",
          "sunrise": 1779755620,
          "sunset": 1779803655
     },
     "timezone": 19800,
     "id": 1258847,
     "name": "Rajkot",
     "cod": 200
}
***************************************************************************************************************************************
***************************************************************************************************************************************
Description : clear sky
Temprature  : 307.11
Pressure    : 1010
Humidity    : 54
Visibility  : 10000
Wind Speed  : 5.93

In [29]:
import requests
def current_weather():
    api_key="c096eadd3c5a43663bee27c7c3b53a05"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    weather_data=response1.json();
    print(json.dumps(weather_data,indent=5))
    q_index={1:"Good",2:"Fair",3:"Moderate",4:"Poor",5:"Very Poor"}
    a=weather_data['list'][0]["main"]["aqi"]
    print(q_index[a])
current_weather()

Enter the City name:  Rajkot

{
     "coord": {
          "lon": 70.8028,
          "lat": 22.3053
     },
     "list": [
          {
               "main": {
                    "aqi": 1
               },
               "components": {
                    "co": 93.47,
                    "no": 0.16,
                    "no2": 0.64,
                    "o3": 36.42,
                    "so2": 0.48,
                    "pm2_5": 6.17,
                    "pm10": 19.5,
                    "nh3": 0.45
               },
               "dt": 1779768089
          }
     ]
}
Good

In [38]:
import requests
def fivedays():
    api_key="c096eadd3c5a43663bee27c7c3b53a05"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    weather_data=response1.json();
    print(json.dumps(weather_data,indent=5))
    return weather_data
five_days=fivedays()

Enter the City name:  Rajkot

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779775200,
               "main": {
                    "temp": 308.38,
                    "feels_like": 311.77,
                    "temp_min": 308.38,
                    "temp_max": 309.82,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 992,
                    "humidity": 43,
                    "temp_kf": -1.44
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.28,
                    "deg": 253,
                    "gust": 5.52
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 06:00:00"
          },
          {
               "dt": 1779786000,
               "main": {
                    "temp": 311.89,
                    "feels_like": 313.91,
                    "temp_min": 311.89,
                    "temp_max": 314,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 989,
                    "humidity": 30,
                    "temp_kf": -2.11
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.49,
                    "deg": 261,
                    "gust": 5.18
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 09:00:00"
          },
          {
               "dt": 1779796800,
               "main": {
                    "temp": 312.06,
                    "feels_like": 314.22,
                    "temp_min": 312.06,
                    "temp_max": 312.06,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 989,
                    "humidity": 30,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.62,
                    "deg": 292,
                    "gust": 6.8
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 12:00:00"
          },
          {
               "dt": 1779807600,
               "main": {
                    "temp": 306.92,
                    "feels_like": 309.52,
                    "temp_min": 306.92,
                    "temp_max": 306.92,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 990,
                    "humidity": 45,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 8.08,
                    "deg": 258,
                    "gust": 8.88
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 15:00:00"
          },
          {
               "dt": 1779818400,
               "main": {
                    "temp": 303.49,
                    "feels_like": 306.64,
                    "temp_min": 303.49,
                    "temp_max": 303.49,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 991,
                    "humidity": 60,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.14,
                    "deg": 258,
                    "gust": 8.49
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 18:00:00"
          },
          {
               "dt": 1779829200,
               "main": {
                    "temp": 301.84,
                    "feels_like": 305.21,
                    "temp_min": 301.84,
                    "temp_max": 301.84,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 991,
                    "humidity": 70,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.44,
                    "deg": 239,
                    "gust": 9.03
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 21:00:00"
          },
          {
               "dt": 1779840000,
               "main": {
                    "temp": 300.7,
                    "feels_like": 304.03,
                    "temp_min": 300.7,
                    "temp_max": 300.7,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 991,
                    "humidity": 79,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.03,
                    "deg": 245,
                    "gust": 9.49
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 00:00:00"
          },
          {
               "dt": 1779850800,
               "main": {
                    "temp": 303.41,
                    "feels_like": 306.28,
                    "temp_min": 303.41,
                    "temp_max": 303.41,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 993,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.07,
                    "deg": 246,
                    "gust": 7.64
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 03:00:00"
          },
          {
               "dt": 1779861600,
               "main": {
                    "temp": 310.69,
                    "feels_like": 310.63,
                    "temp_min": 310.69,
                    "temp_max": 310.69,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 992,
                    "humidity": 26,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.05,
                    "deg": 251,
                    "gust": 6.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 06:00:00"
          },
          {
               "dt": 1779872400,
               "main": {
                    "temp": 314.47,
                    "feels_like": 314.09,
                    "temp_min": 314.47,
                    "temp_max": 314.47,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 990,
                    "humidity": 19,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.59,
                    "deg": 269,
                    "gust": 6.17
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 09:00:00"
          },
          {
               "dt": 1779883200,
               "main": {
                    "temp": 312.39,
                    "feels_like": 313.69,
                    "temp_min": 312.39,
                    "temp_max": 312.39,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 989,
                    "humidity": 27,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 8.24,
                    "deg": 279,
                    "gust": 7.64
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 12:00:00"
          },
          {
               "dt": 1779894000,
               "main": {
                    "temp": 307.29,
                    "feels_like": 309.64,
                    "temp_min": 307.29,
                    "temp_max": 307.29,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 991,
                    "humidity": 43,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 8.01,
                    "deg": 255,
                    "gust": 8.67
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 15:00:00"
          },
          {
               "dt": 1779904800,
               "main": {
                    "temp": 303.36,
                    "feels_like": 306.6,
                    "temp_min": 303.36,
                    "temp_max": 303.36,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 992,
                    "humidity": 61,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.26,
                    "deg": 245,
                    "gust": 8.9
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 18:00:00"
          },
          {
               "dt": 1779915600,
               "main": {
                    "temp": 301.64,
                    "feels_like": 305.28,
                    "temp_min": 301.64,
                    "temp_max": 301.64,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 992,
                    "humidity": 73,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.86,
                    "deg": 233,
                    "gust": 9.12
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 21:00:00"
          },
          {
               "dt": 1779926400,
               "main": {
                    "temp": 300.77,
                    "feels_like": 304.06,
                    "temp_min": 300.77,
                    "temp_max": 300.77,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 992,
                    "humidity": 78,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.78,
                    "deg": 239,
                    "gust": 10.4
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-28 00:00:00"
          },
          {
               "dt": 1779937200,
               "main": {
                    "temp": 303.28,
                    "feels_like": 306.65,
                    "temp_min": 303.28,
                    "temp_max": 303.28,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 994,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.2,
                    "deg": 244,
                    "gust": 9.08
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 03:00:00"
          },
          {
               "dt": 1779948000,
               "main": {
                    "temp": 311.17,
                    "feels_like": 311.08,
                    "temp_min": 311.17,
                    "temp_max": 311.17,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 992,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.63,
                    "deg": 244,
                    "gust": 8.39
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 06:00:00"
          },
          {
               "dt": 1779958800,
               "main": {
                    "temp": 315,
                    "feels_like": 314.48,
                    "temp_min": 315,
                    "temp_max": 315,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 989,
                    "humidity": 18,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 8.16,
                    "deg": 255,
                    "gust": 7.82
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 09:00:00"
          },
          {
               "dt": 1779969600,
               "main": {

In [42]:
import pandas as pd
data={"Date_Time":[],"Description":[],"Temp":[],"Pressure":[],"Humidity":[],"Visibility":[],"Wind Speed":[]}
for i in five_days["list"]:
    data["Date_Time"].append(i['dt_txt'])
    data["Description"].append(i["weather"][0]["description"])
    data["Temp"].append(i["main"]["temp"])
    data["Pressure"].append(i["main"]["pressure"])
    data["Humidity"].append(i["main"]["humidity"])
    data["Visibility"].append(i["visibility"])
    data["Wind Speed"].append(i["wind"]["speed"])
df=pd.DataFrame(data)
df

,Date_Time,Description,Temp,Pressure,Humidity,Visibility,Wind Speed
0,2026-05-26 06:00:00,clear sky,308.38,1009,43,10000,5.28
1,2026-05-26 09:00:00,clear sky,311.89,1006,30,10000,5.49
2,2026-05-26 12:00:00,clear sky,312.06,1005,30,10000,7.62
3,2026-05-26 15:00:00,clear sky,306.92,1007,45,10000,8.08
4,2026-05-26 18:00:00,clear sky,303.49,1008,60,10000,7.14
5,2026-05-26 21:00:00,clear sky,301.84,1007,70,10000,6.44
6,2026-05-27 00:00:00,clear sky,300.70,1008,79,10000,6.03
7,2026-05-27 03:00:00,clear sky,303.41,1010,59,10000,6.07
8,2026-05-27 06:00:00,clear sky,310.69,1009,26,10000,6.05
9,2026-05-27 09:00:00,clear sky,314.47,1006,19,10000,6.59
10,2026-05-27 12:00:00,clear sky,312.39,1005,27,10000,8.24
11,2026-05-27 15:00:00,clear sky,307.29,1007,43,10000,8.01
12,2026-05-27 18:00:00,clear sky,303.36,1009,61,10000,7.26
13,2026-05-27 21:00:00,clear sky,301.64,1008,73,10000,6.86
14,2026-05-28 00:00:00,clear sky,300.77,1008,78,10000,6.78
15,2026-05-28 03:00:00,clear sky,303.28,1010,62,10000,7.20
16,2026-05-28 06:00:00,clear sky,311.17,1008,25,10000,7.63
17,2026-05-28 09:00:00,clear sky,315.00,1006,18,10000,8.16
18,2026-05-28 12:00:00,clear sky,312.62,1005,24,10000,8.80
19,2026-05-28 15:00:00,clear sky,306.70,1007,43,10000,8.06
20,2026-05-28 18:00:00,clear sky,302.79,1007,67,10000,8.13
21,2026-05-28 21:00:00,clear sky,301.24,1006,79,10000,7.87
22,2026-05-29 00:00:00,clear sky,300.70,1008,81,10000,7.22
23,2026-05-29 03:00:00,few clouds,303.56,1009,60,10000,9.06
24,2026-05-29 06:00:00,clear sky,310.25,1008,31,10000,9.32
25,2026-05-29 09:00:00,clear sky,313.03,1005,24,10000,10.26
26,2026-05-29 12:00:00,clear sky,310.79,1004,29,10000,10.70
27,2026-05-29 15:00:00,clear sky,305.62,1005,47,10000,8.97
28,2026-05-29 18:00:00,clear sky,302.32,1004,69,10000,9.42
29,2026-05-29 21:00:00,clear sky,301.15,1003,79,10000,9.09
30,2026-05-30 00:00:00,clear sky,300.65,1004,82,10000,8.48
31,2026-05-30 03:00:00,clear sky,303.69,1005,63,10000,11.01
32,2026-05-30 06:00:00,clear sky,309.54,1004,38,10000,11.68
33,2026-05-30 09:00:00,clear sky,311.59,1002,32,10000,11.74
34,2026-05-30 12:00:00,clear sky,309.45,1002,37,10000,11.24
35,2026-05-30 15:00:00,clear sky,304.20,1003,61,10000,9.18
36,2026-05-30 18:00:00,clear sky,302.08,1004,77,10000,8.69
37,2026-05-30 21:00:00,scattered clouds,301.70,1002,77,10000,8.73
38,2026-05-31 00:00:00,scattered clouds,301.67,1003,74,10000,8.37
39,2026-05-31 03:00:00,scattered clouds,303.75,1005,64,10000,9.61

NASA_API="svXCSVzhsIyVwA0utEJcyae6EPZhUDgnW5fShYGt"

In [45]:
import requests
url="https://api.nasa.gov/planetary/apod"
response=requests.get(url,params={"api_key":"svXCSVzhsIyVwA0utEJcyae6EPZhUDgnW5fShYGt",
                                 "date":"2026-05-26"})
data=response.json()
print(data["url"])

https://apod.nasa.gov/apod/image/2605/Ngc3660Burcin_Block_960.jpg

In [47]:
import requests
url="https://api.nasa.gov/planetary/apod"
response=requests.get(url,params={"api_key":"svXCSVzhsIyVwA0utEJcyae6EPZhUDgnW5fShYGt",
                                 "count":10})
data=response.json()
for i in data:
    print(i["url"])

https://apod.nasa.gov/apod/image/2009/VenusClouds_Akatzuki_960.jpg
https://apod.nasa.gov/apod/image/shapley1_aat.gif
https://apod.nasa.gov/apod/image/0907/m94crop_Paciorek.jpg
https://apod.nasa.gov/apod/image/0112/leonids_kwon.jpg
https://apod.nasa.gov/apod/image/2005/SWAN1_perrot.jpg
https://apod.nasa.gov/apod/image/1403/blackhole_hobart_960.jpg
https://apod.nasa.gov/apod/image/2309/BeautNishimura_Horalek_960.jpg
https://apod.nasa.gov/apod/image/0312/protonaurora_image_big.jpg
https://apod.nasa.gov/apod/image/2512/MontesCaucasusCopie1024.png
https://apod.nasa.gov/apod/image/9611/fractaldust_elw.gif

In [49]:
import requests
url="https://api.nasa.gov/planetary/apod"
response=requests.get(url,params={"api_key":"svXCSVzhsIyVwA0utEJcyae6EPZhUDgnW5fShYGt",
                                 "count":10})
data=response.json()
dates=[]
url=[]
for i in data:
    dates.append(i["date"])
    url.append(i["url"])
df=pd.DataFrame({"Date":dates,"URL":url})
df

         Date                                                URL
0  2009-03-26  https://apod.nasa.gov/apod/image/0903/m46n2438...
1  2012-03-15  https://apod.nasa.gov/apod/image/1203/GraySun2...
2  2015-06-14  https://apod.nasa.gov/apod/image/1506/m101_Hub...
3  1997-04-08  https://apod.nasa.gov/apod/image/9704/halebopp...
4  2006-11-06  https://apod.nasa.gov/apod/image/0611/swan_gra...
5  2006-05-24  https://apod.nasa.gov/apod/image/0605/quasar5p...
6  2021-05-27  https://apod.nasa.gov/apod/image/2105/TLEMay20...
7  2005-11-10  https://apod.nasa.gov/apod/image/0511/gravtug_...
8  2004-09-25  https://apod.nasa.gov/apod/image/0409/feii_eit...
9  2013-06-16  https://apod.nasa.gov/apod/image/1306/apod18_l...